<a href="https://colab.research.google.com/github/Alister44/Melbourne_Housing/blob/main/notebooks/solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings

In [23]:
FILE_IN = 'https://raw.githubusercontent.com/Alister44/Melbourne_Housing/refs/heads/main/data/melb_data_dirty.csv'
df_original = pd.read_csv(FILE_IN)
df = df_original.copy()

Suburb	-  Район  
Address	- Адрес  
Rooms - Количество комнат  
Type - Тип  
Price - Цена  
Method - Способ продажи  
SellerG-Агентство  
Date - Дата(продажи)  
Distance - Расстояние  
Postcode - Почтовый индекс  
Bedroom2 - Спальни  
Bathroom - Ванные комнаты  
Car	Парковочные места  
Landsize	Площадь участка  
BuildingArea	Площадь строения  
YearBuilt	Год постройки  
CouncilArea	Муниципальный округ  
Lattitude	Широта  
Longtitude	Долгота  
Regionname	Регион  
Propertycount	Количество объектов недвижимости в данном районе

# описова статистика числових стовпців

In [34]:
display(df.describe().round(3))

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000,13580.000,13580.000,13580.000,13580.000,13580.000,13518.000,13580.000,7130.000,8205.000,13580.000,13580.000,13580.000
mean,2.938,1075684.079,10.138,3105.302,2.915,1.534,1.610,558.416,151.968,1964.684,-37.809,144.995,7454.417
std,0.956,639310.724,5.869,90.677,0.966,0.692,0.963,3990.669,541.015,37.274,0.079,0.104,4378.582
min,1.000,85000.000,0.000,3000.000,0.000,0.000,0.000,0.000,0.000,1196.000,-38.183,144.432,249.000
25%,2.000,650000.000,6.100,3044.000,2.000,1.000,1.000,177.000,93.000,1940.000,-37.857,144.930,4380.000
50%,3.000,903000.000,9.200,3084.000,3.000,1.000,2.000,440.000,126.000,1970.000,-37.802,145.000,6555.000
75%,3.000,1330000.000,13.000,3148.000,3.000,2.000,2.000,651.000,174.000,1999.000,-37.756,145.058,10331.000
max,10.000,9000000.000,48.100,3977.000,20.000,8.000,10.000,433014.000,44515.000,2018.000,-37.409,145.526,21650.000

описова статистика всіх стопвпців

In [36]:
display(df.describe(include='all'))

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
count,13580,13580,13580.000000,13580,1.358000e+04,13580,13580,13580,13580.000000,13580.000000,...,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,12211,13580.000000,13580.000000,13580,13580.000000
unique,314,13378,NaN,3,NaN,5,268,58,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,33,NaN,NaN,8,NaN
top,Reservoir,5 Margaret St,NaN,h,NaN,S,Nelson,27/05/2017,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Moreland,NaN,NaN,Southern Metropolitan,NaN
freq,359,3,NaN,9449,NaN,9022,1565,473,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1163,NaN,NaN,4695,NaN
mean,NaN,NaN,2.937997,NaN,1.075684e+06,NaN,NaN,NaN,10.137776,3105.301915,...,1.534242,1.610075,558.416127,151.967650,1964.684217,NaN,-37.809203,144.995216,NaN,7454.417378
std,NaN,NaN,0.955748,NaN,6.393107e+05,NaN,NaN,NaN,5.868725,90.676964,...,0.691712,0.962634,3990.669241,541.014538,37.273762,NaN,0.079260,0.103916,NaN,4378.581772
min,NaN,NaN,1.000000,NaN,8.500000e+04,NaN,NaN,NaN,0.000000,3000.000000,...,0.000000,0.000000,0.000000,0.000000,1196.000000,NaN,-38.182550,144.431810,NaN,249.000000
25%,NaN,NaN,2.000000,NaN,6.500000e+05,NaN,NaN,NaN,6.100000,3044.000000,...,1.000000,1.000000,177.000000,93.000000,1940.000000,NaN,-37.856822,144.929600,NaN,4380.000000
50%,NaN,NaN,3.000000,NaN,9.030000e+05,NaN,NaN,NaN,9.200000,3084.000000,...,1.000000,2.000000,440.000000,126.000000,1970.000000,NaN,-37.802355,145.000100,NaN,6555.000000
75%,NaN,NaN,3.000000,NaN,1.330000e+06,NaN,NaN,NaN,13.000000,3148.000000,...,2.000000,2.000000,651.000000,174.000000,1999.000000,NaN,-37.756400,145.058305,NaN,10331.000000
max,NaN,NaN,10.000000,NaN,9.000000e+06,NaN,NaN,NaN,48.100000,3977.000000,...,8.000000,10.000000,433014.000000,44515.000000,2018.000000,NaN,-37.408530,145.526350,NaN,21650.000000

Анализ пропущенных значений и типов

In [31]:
info = pd.DataFrame({
    "тип": df.dtypes.astype(str),
    'кількість пропусків': df.isnull().sum(),
    "пропусків_%": (df.isna().mean() * 100).round(1),
})
print(info.sort_values("пропусків_%", ascending=False))

                   тип  кількість пропусків  пропусків_%
BuildingArea   float64                 6450         47.5
YearBuilt      float64                 5375         39.6
CouncilArea     object                 1369         10.1
Car            float64                   62          0.5
Suburb          object                    0          0.0
Price          float64                    0          0.0
Type            object                    0          0.0
Rooms            int64                    0          0.0
Address         object                    0          0.0
Distance       float64                    0          0.0
Method          object                    0          0.0
Date            object                    0          0.0
SellerG         object                    0          0.0
Bathroom       float64                    0          0.0
Bedroom2       float64                    0          0.0
Postcode       float64                    0          0.0
Landsize       float64                    0          0.0
Lattitude      float64                    0          0.0
Longtitude     float64                    0          0.0
Regionname      object                    0          0.0
Propertycount  float64                    0          0.0

Перевірка чи немає технічного стовпця-індексу, який потрапив у файл.Якщо є - прибераєм

In [38]:
clean = df.copy()
if 'Unnamed: 0' in clean.columns:
  clean = clean.drop(columns=['Unnamed: 0'])
  print('Column with index - deleted')